version: '3.5'
services:
  bedrock-server:
    image: ghcr.io/vija02/modern-wp-setup:main
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"
    labels:
      caddy: example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.reverse_proxy.transport: "http"
